openapi: 3.0.0
info:
  title: Citation Tracker Tool
  description: Tracks and formats citations for generated answers
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Citation Tracker API
paths:
  /track_citations:
    post:
      summary: Track answer citations
      description: Format citations and generate bibliography
      operationId: track_citations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer_text:
                  type: string
                  description: The generated answer
                source_emails:
                  type: array
                  items:
                    type: string
                  description: Email IDs used as sources
              required:
                - answer_text
                - source_emails
      responses:
        '200':
          description: Citations tracked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  cited_answer:
                    type: string
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        text_fragment:
                          type: string
                        source_email_id:
                          type: string
                  bibliography:
                    type: array
                    items:
                      type: string
