openapi: 3.0.0
info:
  title: Context Retriever Tool
  description: Retrieves relevant email context for questions
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Context Retriever API
paths:
  /retrieve_context:
    post:
      summary: Retrieve email context
      description: Search and retrieve relevant context based on question
      operationId: retrieve_context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: The question to find context for
                max_results:
                  type: integer
                  description: Maximum number of results (default 5)
              required:
                - question
      responses:
        '200':
          description: Context retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        email_id:
                          type: string
                        relevance:
                          type: number
                        excerpt:
                          type: string
